config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

	devise_for :users, :controllers => { :registrations => 'users/registrations' }
	devise_scope :user do  
	   get '/users/sign_out' => 'devise/sessions#destroy'  
	end

	get 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
	get 'users/:id' => 'users#show', as: :user
	resources :users

  root 'pages#index'
  #root to: "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader

  # instead of deleting, indicate the user requested a delete & timestamp it  
  def soft_delete  
    update_attribute(:deleted_at, Time.current)  
  end  

  # ensure user account is active  
  def active_for_authentication?  
    super && !deleted_at  
  end  

  # provide a custom message for a deleted account   
  def inactive_message   
    !deleted_at ? super : :deleted_account  
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone, :email, :avatar])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # DELETE /resource  
  def destroy  
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)  
    set_flash_message :notice, :destroyed if is_flashing_format?  
    yield resource if block_given?  
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }  
  end  
end  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@user = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
        redirect_to root_url, notice: "User deleted."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Project name
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li.active
          %a{:href => "/"} Home
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
            %span.caret
          %ul.dropdown-menu
            %li
              %a{:href => "#"} Action
            %li
              %a{:href => "#"} Another action
            %li
              %a{:href => "#"} Something else here
            %li.divider{:role => "separator"}
            %li.dropdown-header Nav header
            %li
              %a{:href => "#"} Separated link
            %li
              %a{:href => "#"} One more separated link
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to "Sign Out", destroy_user_session_path, :method => :delete
          %li
            = link_to "Edit profile", edit_user_registration_path
        - else
          %li
            = link_to "Sign in", new_user_session_path 
       
          
    / /.nav-collapse
  / /.container-fluid

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Ads
    = csrf_meta_tags
    
    %script{:src => "//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"}
    %script{:src => "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"}
    %link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", :rel => "stylesheet", :type => "text/css"}/
  %body
    .container-fluid
      .row
        %p.notice= notice
        %p.alert= alert
      .row
        .col-md-12
          = render partial: "layouts/nav"
      .row
        .col-md-12
          = yield
      .row
        .col-md-12
          %br/
          = debug(params) if Rails.env.development?

app/views/pages/index.html.haml
%h1 Labas!

app/views/users/_user.html.erb
<div class="comments">
  <%= link_to user.name, user %>
  <% if current_user.try(:admin?) && !current_user?(user) %>
       <%= link_to "Destroy", admin_destroy_user_path(user), method: :delete, data: { confirm: "You sure?" } %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class = "container">
    <div id="usersview">
    <b>USERS DIRECTORY</b>
    <%= render @users %>
</div>
</div>